name: moods
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.2.2
  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  flutter_riverpod: ^2.6.1
  kakao_flutter_sdk_user: 1.6.0
  kakao_flutter_sdk_auth: 1.6.0
  image_picker: ^1.2.0
  path_provider: ^2.1.3
  path: ^1.9.0
  blur: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/icons/home.svg
    - assets/fonts/icons/home_selected.svg
    - assets/fonts/icons/thumb.svg
    - assets/fonts/icons/thumb_selected.svg
    - assets/fonts/icons/map.svg
    - assets/fonts/icons/map_selected.svg
    - assets/fonts/icons/mypage.svg
    - assets/fonts/icons/mypage_selected.svg
    - assets/fonts/icons/calender.svg
    - assets/fonts/icons/kakao.svg
    - assets/fonts/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
